/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.7
 * Generated at: 2023-10-10 21:16:33 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.frontend;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("  <!DOCTYPE html>\n");
      out.write("  <html lang=\"en\">\n");
      out.write("\n");
      out.write("  <head>\n");
      out.write("    <meta charset=\"utf-8\">\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n");
      out.write("\n");
      out.write("    <link rel=\"icon\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${BASE_URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/resources/img/logo.svg\">\n");
      out.write("    <title>Happy Cart | Log in</title>\n");
      out.write("\n");
      out.write("    <!-- Google Font: Source Sans Pro -->\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback\">\n");
      out.write("    <!-- Font Awesome -->\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${BASE_URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/plugins/fontawesome-free/css/all.min.css\">\n");
      out.write("    <!-- icheck bootstrap -->\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${BASE_URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/plugins/icheck-bootstrap/icheck-bootstrap.min.css\">\n");
      out.write("    <!-- Theme style -->\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${BASE_URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/dist/css/adminlte.min.css\">\n");
      out.write("\n");
      out.write("\n");
      out.write("    <!-- SweetAlert2 -->\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${BASE_URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/plugins/sweetalert2-theme-bootstrap-4/bootstrap-4.min.css\">\n");
      out.write("    <!-- Toastr -->\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${BASE_URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/plugins/toastr/toastr.min.css\">\n");
      out.write("\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${BASE_URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/style.css\">\n");
      out.write("  </head>\n");
      out.write("\n");
      out.write("  <body class=\"hold-transition login-page\" style=\"background-color: #74EBD5; background-image: linear-gradient(90deg,#74EBD5 0%,#9FACE6 100%);\">\n");
      out.write("    <div class=\"alert alert-success d-none\" id=\"alart\">\n");
      out.write("    </div>\n");
      out.write("    <div class=\"login-box\">\n");
      out.write("      <!-- /.login-logo -->\n");
      out.write("      <div class=\"card card-outline card-primary\">\n");
      out.write("        <div class=\"card-header text-center\">\n");
      out.write("          <a href=\"index\" class=\"h1\"><b>Happy Cart</b></a>\n");
      out.write("        </div>\n");
      out.write("        <div class=\"card-body\">\n");
      out.write("          <p class=\"login-box-msg\">Welcome to Happy Cart</p>\n");
      out.write("\n");
      out.write("          <form action=\"index3.html\" method=\"post\">\n");
      out.write("            <div class=\"input-group mb-3\">\n");
      out.write("              <input type=\"email\" class=\"form-control\" placeholder=\"Email\" id=\"e\">\n");
      out.write("              <div class=\"input-group-append\">\n");
      out.write("                <div class=\"input-group-text\">\n");
      out.write("                  <span class=\"fas fa-envelope\"></span>\n");
      out.write("                </div>\n");
      out.write("              </div>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"input-group mb-3\">\n");
      out.write("              <input type=\"password\" class=\"form-control\" placeholder=\"Password\" id=\"pw\">\n");
      out.write("              <div class=\"input-group-append\">\n");
      out.write("                <div class=\"input-group-text\">\n");
      out.write("                  <span class=\"fas fa-lock\"></span>\n");
      out.write("                </div>\n");
      out.write("              </div>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"row\">\n");
      out.write("              <div class=\"col-8\">\n");
      out.write("                <div class=\"icheck-primary\">\n");
      out.write("                  <input type=\"checkbox\" id=\"remember\">\n");
      out.write("                  <label for=\"remember\">\n");
      out.write("                    Remember Me\n");
      out.write("                  </label>\n");
      out.write("                </div>\n");
      out.write("              </div>\n");
      out.write("              <!-- /.col -->\n");
      out.write("              <div class=\"col-4\">\n");
      out.write("                <button type=\"button\" class=\"btn btn-primary btn-block swalDefaultWarning sign-up12\" >Sign In</button>\n");
      out.write("              </div>\n");
      out.write("              <!-- /.col -->\n");
      out.write("            </div>\n");
      out.write("          </form>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("          <p class=\"mb-1\">\n");
      out.write("            <a href=\"#\" onclick=\"forgotPassword();\">I forgot my password</a>\n");
      out.write("          </p>\n");
      out.write("          <p class=\"mb-0\">\n");
      out.write("            <a href=\"register\" class=\"text-center\">Register a new membership</a>\n");
      out.write("          </p>\n");
      out.write("        </div>\n");
      out.write("        <!-- /.card-body -->\n");
      out.write("      </div>\n");
      out.write("      <!-- /.card -->\n");
      out.write("    </div>\n");
      out.write("    <!-- /.login-box -->\n");
      out.write("\n");
      out.write("    <!-- model -->\n");
      out.write("\n");
      out.write("    <div class=\"modal\" tabindex=\"-1\" id=\"fogotPasswordModel\">\n");
      out.write("      <div class=\"modal-dialog\">\n");
      out.write("        <div class=\"modal-content\">\n");
      out.write("          <div class=\"modal-header\">\n");
      out.write("            <h5 class=\"modal-title\">Modal title</h5>\n");
      out.write("\n");
      out.write("          </div>\n");
      out.write("          <div class=\"modal-body\">\n");
      out.write("\n");
      out.write("            <div class=\"row g-3\">\n");
      out.write("\n");
      out.write("              <div class=\"col-6\">\n");
      out.write("                <label class=\"form-label\">New Password</label>\n");
      out.write("                <div class=\"input-group mb-3\">\n");
      out.write("                  <input type=\"password\" class=\"form-control\" placeholder=\"Recipient's username\" aria-label=\"Recipient's username\" aria-describedby=\"basic-addon2\" id=\"np\">\n");
      out.write("\n");
      out.write("                  <button class=\"btn btn-secondary\" type=\"button\" id=\"npb\" onclick=\"showpassword1();\"><i class=\"bi bi-eye-slash-fill\">Show</i></button>\n");
      out.write("                </div>\n");
      out.write("\n");
      out.write("              </div>\n");
      out.write("              <div class=\"col-6\">\n");
      out.write("                <label class=\"form-label\">Re-Type Password</label>\n");
      out.write("                <div class=\"input-group mb-3\">\n");
      out.write("                  <input type=\"password\" class=\"form-control\" id=\"rnp\">\n");
      out.write("\n");
      out.write("                  <button class=\"btn btn-secondary\" type=\"button\" id=\"rnpb\" onclick=\"showpassword2();\"><i class=\"bi bi-eye-slash-fill\">Show</i></button>\n");
      out.write("                </div>\n");
      out.write("\n");
      out.write("              </div>\n");
      out.write("\n");
      out.write("              <div class=\"col-6\">\n");
      out.write("                <label class=\"form-label\">Verification Code</label>\n");
      out.write("                <div class=\"input-group mb-3\">\n");
      out.write("                  <input type=\"text\" class=\"form-control\" id=\"vc\">\n");
      out.write("                </div>\n");
      out.write("\n");
      out.write("              </div>\n");
      out.write("              <p>Verification code has send to your email. please check inbox.</p>\n");
      out.write("            </div>\n");
      out.write("          </div>\n");
      out.write("          <div class=\"modal-footer\">\n");
      out.write("            <button type=\"button\" class=\"btn btn-secondary\" data-bs-dismiss=\"modal\">Close</button>\n");
      out.write("            <button type=\"button\" class=\"btn btn-primary\" onclick=\"resetpassword();\">Reset</button>\n");
      out.write("          </div>\n");
      out.write("        </div>\n");
      out.write("      </div>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    <!-- model -->\n");
      out.write("\n");
      out.write("\n");
      out.write("    <!-- jQuery -->\n");
      out.write("    <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${BASE_URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/plugins/jquery/jquery.min.js\"></script>\n");
      out.write("    <!-- Bootstrap 4 -->\n");
      out.write("    <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${BASE_URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/plugins/bootstrap/js/bootstrap.bundle.min.js\"></script>\n");
      out.write("    <!-- AdminLTE App -->\n");
      out.write("    <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${BASE_URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/dist/js/adminlte.min.js\"></script>\n");
      out.write("\n");
      out.write("    <!-- SweetAlert2 -->\n");
      out.write("    <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${BASE_URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/plugins/sweetalert2/sweetalert2.min.js\"></script>\n");
      out.write("    <!-- Toastr -->\n");
      out.write("    <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${BASE_URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/plugins/toastr/toastr.min.js\"></script>\n");
      out.write("    <!-- AdminLTE for demo purposes -->\n");
      out.write("    <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${BASE_URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/dist/js/demo.js\"></script>\n");
      out.write("    <!-- Page specific script -->\n");
      out.write("\n");
      out.write("    <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${BASE_URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/bootstrap.js\"></script>\n");
      out.write("    <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${BASE_URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/script.js\"></script>\n");
      out.write("\n");
      out.write("  </body>\n");
      out.write("\n");
      out.write("  </html>\n");
      out.write("  <script type=\"text/javascript\">\n");
      out.write("\n");
      out.write("\n");
      out.write("    document.getElementsByClassName('sign-up12').item(0).addEventListener('click', function () {\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("      var email = document.getElementById(\"e\").value;\n");
      out.write("      var password = document.getElementById(\"pw\").value;\n");
      out.write("      var rememberme = document.getElementById(\"remember\").checked;\n");
      out.write("\n");
      out.write("      fetch('login',{\n");
      out.write("        method:'post',\n");
      out.write("        headers:{\n");
      out.write("          'Content-Type':'application/json'\n");
      out.write("        },\n");
      out.write("        body:JSON.stringify({\n");
      out.write("          password:password,\n");
      out.write("          email:email,\n");
      out.write("          rememberme:rememberme\n");
      out.write("        })\n");
      out.write("      }) .then(function(response) {\n");
      out.write("        if (response.status === 200) {\n");
      out.write("          // Handle successful response\n");
      out.write("          // Change the URL using JavaScript\n");
      out.write("          window.location.href = 'index';\n");
      out.write("        } else if(response.status===403) {\n");
      out.write("          alert(\"Please Confirm Your Email\");\n");
      out.write("        }else {\n");
      out.write("          // Handle other response status codes\n");
      out.write("          console.error('Request failed with status:', response.status);\n");
      out.write("          alert(\"Invalid Email or Password\");\n");
      out.write("        }\n");
      out.write("      })\n");
      out.write("              .catch(function(error) {\n");
      out.write("                // Handle network or other errors\n");
      out.write("                console.error('Request failed:', error);\n");
      out.write("              });\n");
      out.write("\n");
      out.write("    });\n");
      out.write("\n");
      out.write("\n");
      out.write("  </script>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
