/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.7
 * Generated at: 2023-10-10 20:05:24 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.frontend;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class register_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("\n");
      out.write("<head>\n");
      out.write("  <meta charset=\"utf-8\">\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n");
      out.write("  <link rel=\"icon\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${BASE_URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/resources/img/logo.svg\">\n");
      out.write("  <title>Happy Cart | Registration Page</title>\n");
      out.write("\n");
      out.write("  <!-- Google Font: Source Sans Pro -->\n");
      out.write("  <link rel=\"stylesheet\" href=\"https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback\">\n");
      out.write("  <!-- Font Awesome -->\n");
      out.write("  <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${BASE_URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/plugins/fontawesome-free/css/all.min.css\">\n");
      out.write("  <!-- icheck bootstrap -->\n");
      out.write("  <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${BASE_URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/plugins/icheck-bootstrap/icheck-bootstrap.min.css\">\n");
      out.write("  <!-- Theme style -->\n");
      out.write("  <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${BASE_URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/dist/css/adminlte.min.css\">\n");
      out.write("\n");
      out.write("\n");
      out.write("  <!-- SweetAlert2 -->\n");
      out.write("  <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${BASE_URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/plugins/sweetalert2-theme-bootstrap-4/bootstrap-4.min.css\">\n");
      out.write("  <!-- Toastr -->\n");
      out.write("  <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${BASE_URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/plugins/toastr/toastr.min.css\">\n");
      out.write("</head>\n");
      out.write("\n");
      out.write("<body class=\"hold-transition register-page \" style=\"background-color: #74EBD5; background-image: linear-gradient(90deg,#74EBD5 0%,#9FACE6 100%);\">\n");
      out.write("  <div class=\"register-box\">\n");
      out.write("    <div class=\"card card-outline card-primary \">\n");
      out.write("      <div class=\"card-header text-center\">\n");
      out.write("        <a href=\"index2.jsp\" class=\"h1\"><b>Happy Cart</b></a>\n");
      out.write("      </div>\n");
      out.write("      <div class=\"card-body\">\n");
      out.write("        <p class=\"login-box-msg\">Register a new membership</p>\n");
      out.write("\n");
      out.write("        <form action=\"index.jsp\" method=\"post\">\n");
      out.write("          <div class=\"input-group mb-3\">\n");
      out.write("            <input type=\"text\" class=\"form-control\" placeholder=\"First name\" id=\"fname\">\n");
      out.write("            <div class=\"input-group-append\">\n");
      out.write("              <div class=\"input-group-text\">\n");
      out.write("                <span class=\"fas fa-user\"></span>\n");
      out.write("              </div>\n");
      out.write("            </div>\n");
      out.write("          </div>\n");
      out.write("\n");
      out.write("          <div class=\"input-group mb-3\">\n");
      out.write("            <input type=\"text\" class=\"form-control\" placeholder=\"Last name\" id=\"lname\">\n");
      out.write("            <div class=\"input-group-append\">\n");
      out.write("              <div class=\"input-group-text\">\n");
      out.write("                <span class=\"fas fa-user\"></span>\n");
      out.write("              </div>\n");
      out.write("            </div>\n");
      out.write("          </div>\n");
      out.write("\n");
      out.write("          <div class=\"input-group mb-3\">\n");
      out.write("            <input type=\"email\" class=\"form-control\" placeholder=\"Email\" id=\"email\">\n");
      out.write("            <div class=\"input-group-append\">\n");
      out.write("              <div class=\"input-group-text\">\n");
      out.write("                <span class=\"fas fa-envelope\"></span>\n");
      out.write("              </div>\n");
      out.write("            </div>\n");
      out.write("          </div>\n");
      out.write("          <div class=\"input-group mb-3\">\n");
      out.write("            <input type=\"password\" class=\"form-control\" placeholder=\"Password\" id=\"password\">\n");
      out.write("            <div class=\"input-group-append\">\n");
      out.write("              <div class=\"input-group-text\">\n");
      out.write("                <span class=\"fas fa-lock\"></span>\n");
      out.write("              </div>\n");
      out.write("            </div>\n");
      out.write("          </div>\n");
      out.write("          <div class=\"input-group mb-3\">\n");
      out.write("            <input type=\"password\" class=\"form-control\" placeholder=\"Retype password\" id=\"repassword\">\n");
      out.write("            <div class=\"input-group-append\">\n");
      out.write("              <div class=\"input-group-text\">\n");
      out.write("                <span class=\"fas fa-lock\"></span>\n");
      out.write("              </div>\n");
      out.write("            </div>\n");
      out.write("          </div>\n");
      out.write("\n");
      out.write("          <div class=\"form-group\">\n");
      out.write("            <select class=\"form-control\" id=\"gender\">\n");
      out.write("              <option selected disabled value=\"SELECT\">Select one</option>\n");
      out.write("              <option value=\"MALE\">Male</option>\n");
      out.write("              <option value=\"FEMALE\">Female</option>\n");
      out.write("            </select>\n");
      out.write("          </div>\n");
      out.write("\n");
      out.write("          <div class=\"row\">\n");
      out.write("            <div class=\"col-8\">\n");
      out.write("              <div class=\"icheck-primary\">\n");
      out.write("                <input type=\"checkbox\" id=\"agreeTerms\" name=\"terms\" value=\"agree\">\n");
      out.write("                <label for=\"agreeTerms\" id=\"agree\">\n");
      out.write("                  I agree to the <a href=\"#\">terms</a>\n");
      out.write("                </label>\n");
      out.write("              </div>\n");
      out.write("            </div>\n");
      out.write("            <!-- /.col -->\n");
      out.write("            <div class=\"col-4\">\n");
      out.write("              <button type=\"button\" class=\"btn btn-primary btn-block swalDefaultWarning sign-up12\" >Register</button>\n");
      out.write("            </div>\n");
      out.write("            <!-- /.col -->\n");
      out.write("          </div>\n");
      out.write("        </form>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("        <a href=\"login\" class=\"text-center\">I already have a membership</a>\n");
      out.write("      </div>\n");
      out.write("      <!-- /.form-box -->\n");
      out.write("    </div><!-- /.card -->\n");
      out.write("  </div>\n");
      out.write("  <!-- /.register-box -->\n");
      out.write("\n");
      out.write("  <!-- jQuery -->\n");
      out.write("  <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${BASE_URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/plugins/jquery/jquery.min.js\"></script>\n");
      out.write("  <!-- Bootstrap 4 -->\n");
      out.write("  <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${BASE_URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/plugins/bootstrap/js/bootstrap.bundle.min.js\"></script>\n");
      out.write("  <!-- AdminLTE App -->\n");
      out.write("  <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${BASE_URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/dist/js/adminlte.min.js\"></script>\n");
      out.write("\n");
      out.write("  <!-- SweetAlert2 -->\n");
      out.write("  <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${BASE_URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/plugins/sweetalert2/sweetalert2.min.js\"></script>\n");
      out.write("  <!-- Toastr -->\n");
      out.write("  <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${BASE_URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/plugins/toastr/toastr.min.js\"></script>\n");
      out.write("  <!-- AdminLTE for demo purposes -->\n");
      out.write("  <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${BASE_URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/dist/js/demo.js\"></script>\n");
      out.write("  <!-- Page specific script -->\n");
      out.write("  <script>\n");
      out.write("\n");
      out.write("  </script>\n");
      out.write("\n");
      out.write("  <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${BASE_URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/script.js\"></script>\n");
      out.write("</body>\n");
      out.write("  <script type=\"text/javascript\">\n");
      out.write("\n");
      out.write("\n");
      out.write("    document.getElementsByClassName('sign-up12').item(0).addEventListener('click', function () {\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("      var fname = document.getElementById(\"fname\").value;\n");
      out.write("      var lname = document.getElementById(\"lname\").value;\n");
      out.write("      var email = document.getElementById(\"email\").value;\n");
      out.write("      var password = document.getElementById(\"password\").value;\n");
      out.write("      var repassword = document.getElementById(\"repassword\").value;\n");
      out.write("      var gender = document.getElementById(\"gender\").value;\n");
      out.write("      var agreeTerms = document.getElementById(\"agreeTerms\").checked;\n");
      out.write("      // alert(\"abct\");\n");
      out.write("\n");
      out.write("      fetch('register',{\n");
      out.write("        method:'post',\n");
      out.write("        headers:{\n");
      out.write("          'Content-Type':'application/json'\n");
      out.write("        },\n");
      out.write("        body:JSON.stringify({\n");
      out.write("          password:password,\n");
      out.write("          fname:fname,\n");
      out.write("          lname:lname,\n");
      out.write("          email:email,\n");
      out.write("          repassword:repassword,\n");
      out.write("          gender:gender,\n");
      out.write("          agreeTerms:agreeTerms\n");
      out.write("        })\n");
      out.write("      }).then(response=> response.text())\n");
      out.write("              .then(text=>document.body.innerHTML=text);\n");
      out.write("\n");
      out.write("    });\n");
      out.write("\n");
      out.write("\n");
      out.write("  </script>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
